services:
  nginx:
    image: rohittp0/nginx-secure:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MAPPINGS=${HOST}=grafana:3000,loki.${HOST}=loki:3100
      - SSL_ENABLED=true
      - DEBUG=true
    volumes:
      - certs:/etc/letsencrypt/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf.template:/app/default.conf.template:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
  certs:
