services:
  nginx:
    container_name: nginx
    image: rohittp0/nginx-secure:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MAPPINGS=${HOST}=grafana:3000,loki.${HOST}=loki:3100,prom.${HOST}=prom:9090
      - SSL_ENABLED=true
      - DEBUG=true
    volumes:
      - certs:/etc/letsencrypt/
      - ./loki.3100.conf:/app/loki.3100.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - monitoring

  prom:
    image: prom/prometheus:latest
    container_name: prom
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    depends_on:
      - alertmanager
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prom
      - loki
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    volumes:
      - loki_data:/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  loki_data:
  alertmanager_data:
  grafana_data:
  certs:
